spring.application.name=sys

server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root1234

# spring.datasource.url=jdbc:mysql://localhost:3306/user
# spring.datasource.username=root
# spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

cloudinary.cloud_name=dptbmikjg
cloudinary.api_key=753994999189293
cloudinary.api_secret=EkoatRvOdXwC7-37gGr5MHVO_Rg

spring.data.redis.host=redis-19630.c14.us-east-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=19630
spring.data.redis.password=HWOZkDsvSv5Jx5vSbws6XFFuFR1wSxpQ
# spring.data.redis.ssl.enabled=true

# @Bean
# public Cloudinary cloudinary() {
#     return new Cloudinary(ObjectUtils.asMap(
#         "cloud_name", "dptbmikjg",
#         "api_key", "753994999189293",
#         "api_secret", "EkoatRvOdXwC7-37gGr5MHVO_Rg"
#     ));
# }
